export {
  add_color_stop,
  create_image,
  create_linear_gradient,
  create_pattern,
  create_radial_gradient,
  create_string,
  get_image_data,
  put_image_data,
  put_image_data_dirty,
  remove_image,
  remove_gradient,
  remove_pattern,
  render,
  report_image_loaded,
  report_use_canvas,
  report_use_image,
  log,
} from "./util";
