export {
  add_color_stop,
  create_image,
  create_linear_gradient,
  create_pattern,
  create_radial_gradient,
  create_string,
  remove_image,
  remove_gradient,
  remove_pattern,
  render,
  report_image_loaded,
  report_use_canvas,
  report_use_image,
} from "./util";
